apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
spec:
  hostAliases:
  - ip: "172.16.34.56"
    hostnames:
    - "test.abc.com"
    - "abc.test.com"
  - ip: "10.24.133.196"
    hostnames:
    - ""
 
  containers:
  - name:  jnlp
    image: jenkinsci/jnlp-slave
  - name: jenkins-agent
    image: jenkins-agent-custom:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run
      type: Directory